version: "3.9"

services:
    app:
        container_name: oba-custom-content
        image: oba-custom-content
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "8080:8080"
